# Generated by Django 4.2.4 on 2023-08-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
